from django.shortcuts import render
# from src.main import main_generate
from src.utils.get_stats import generate_stats_string
from src.utils.update_user import update_user
from src.utils.generate_topster import main_generate
import time
import asyncio

def home(request):
    print("test")
    return render(request, "home.html", {})

def your_stats(request):
    filename = request.POST['receive_key-stats']
    print(filename)
    stats = generate_stats_string(filename)
    f = open(f'image_generation/templates/your-stats.html', "w") 
    f.write(f'''
{{% load static %}}

<h1>{filename} Stats:</h1>
    <p>This page and image are autogenerated</p>
    <p>{stats}<p>
            ''')
    f.close()
    return render(request, f"your-stats.html", {})

def your_name(request):
    filename = request.POST['receive_key-name']
    x = main_generate(filename)
    print(x)
    f = open(f'image_generation/templates/your-name.html', "w") 
    f.write(f'''
{{% load static %}}

<h1>{filename} Topster:</h1>
    <p>This page and image are autogenerated</p>
    <img src="{{% static './media/{filename}.png' %}}" width="500" height="600">
            ''')
    f.close()
    return render(request, f"your-name.html", {})

async def your_update(request):
    filename = request.POST['receive_key-update']
    # TODO needs to be async if we want to exit out of this window
    loop = asyncio.get_event_loop()
    loop.create_task(update_user(filename))
    # x = update_user(filename)
    # print(x)
    # continue on 
    f = open(f'image_generation/templates/your-update.html', "w") 
    f.write(f'''
{{% load static %}}

<h1>Generating Stats for {filename}...</h1>
    <p>Thank you for submitting your username<br><br>
        We're extracting your information now which may take a few minutes.<br><br>
        Feel free to exit and return in some time to request your topster or stats</p>
            ''')
    f.close()
    return render(request, f"your-update.html", {})
