from django.shortcuts import render
from src.main import main_generate
from src.utils.get_stats import generate_stats_string
import time

def home(request):
    print("test")
    return render(request, "home.html", {})

# def your_name(request):
#     # print(request.POST)
#     filename = request.POST['receive_key-name']
#     # print(filename)
#     x = main_generate(filename)
#     print(x)
#     f = open(f'image_generation/templates/{filename}.html', "w") 
#     f.write(f'''
# {{% load static %}}

# <h1>Image Output</h1>
#     <p>Auto generated page with the image:</p>
#     <img src="{{% static './media/{filename}.png' %}}" width="500" height="600">
#             ''')
#     f.close()
#     return render(request, f"{filename}.html", {})

def your_name(request):
    # print(request.POST)
    filename = request.POST['receive_key-name']
    # print(filename)
    x = main_generate(filename)
    print(x)
    stats = generate_stats_string(filename)
    f = open(f'image_generation/templates/your-name.html', "w") 
    f.write(f'''
{{% load static %}}

<h1>{filename} Topster:</h1>
    <p>This page and image are autogenerated</p>
    <p>{stats}<p>
    <img src="{{% static './media/{filename}.png' %}}" width="500" height="600">
            ''')
    f.close()
    return render(request, f"your-name.html", {})
