# Generated by Django 4.0.3 on 2023-12-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_item2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('type', models.TextField()),
                ('director', models.TextField()),
                ('dateModified', models.TextField()),
                ('productionCompany', models.TextField()),
                ('releasedEvent', models.TextField()),
                ('url', models.TextField()),
                ('actors', models.TextField()),
                ('dateCreated', models.TextField()),
                ('name', models.TextField()),
                ('reviewCount', models.TextField()),
                ('ratingValue', models.TextField()),
                ('ratingCount', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
