# Generated by Django 4.0.3 on 2023-12-10 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_movieinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo',
            name='type',
        ),
    ]
