# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory to /app
WORKDIR /app

# Copy the entire project to the container
COPY . /app

# Install poetry and project dependencies
RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi

# Set the entry point to the script
ENTRYPOINT ["poetry", "run", "python", "src/update_user.py"]
